# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2  # Use the version 2 of the configuration file

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04  # Specify the build environment's operating system
  tools:
    python: "3.12"  # Specify the Python version used for the build

# Configuration for MkDocs
# Declare the MkDocs configuration file
mkdocs:
  configuration: mkdocs.yml  # Path to the MkDocs configuration file

# Optionally declare the Python requirements required to build your docs
# List any dependencies needed for building your documentation
python:
 
